### ISSUE TITLE
File Name Case

### ISSUE THREAD

**Issue by BHLabsLtd** [Sensirion/arduino-i2c-sht4x#10]
I can't update to the latest version on Platform IO due to the file name.  i can't even pull the branch without git getting really confused.

i didn't know Mac was case Insensitive but i guess it is now? 

the file images/sht4x.png also does it with SHT4x.png 

i'm on M3 Mac Book Pro
MacOS Sonoma 14.7.1.

when i pull the branch i get "changes need to be committed" over and over and platform io can't use the lib.

git reset just sends it in a big circle switching between the 2 files.

when i reset i get this

-#ifndef SENSIRIONI2CSHT4X_COMPAT_H
-#define SENSIRIONI2CSHT4X_COMPAT_H
+#ifndef SENSIRIONI2CSHT4X_H
+#define SENSIRIONI2CSHT4X_H

then reset again i get this and visa versa!

-return Converted from ticks to degrees celsius by...
-static float signalTemperature(uint16_t temperatureTicks);

+#ifndef SENSIRIONI2CSHT4X_COMPAT_H
+#define SENSIRIONI2CSHT4X_COMPAT_H

**Comment by LeonieFierz** [comment]
Hi @BHLabsLtd 

I did test on Linux and thus was not aware of the name conflict, sorry for the inconvenience.
We removed the old image and removed the compatibility header again. 
You should be able to checkout and use the Repo now. 

Best, Léonie

**Comment by BHLabsLtd** [comment]
Hi @LeonieFierz 

Thank you for fixing this so fast!  Now i can import the lib and use it properly.   👍
