### ISSUE TITLE
Small mistake in documentation

### ISSUE THREAD

**Issue by F-Schmidt99** [Sensirion/arduino-i2c-sht4x#2]
In class SensirionI2CSht4x.cpp the documentation says (line 53):

`* @param serial Arduino stream object to be communicated with.`

Should be:

`* @param i2cBus Arduino stream object to be communicated with.`

**Comment by psachs** [comment]
Thanks for pointing that out, we will fix the documentation in an updated version

**Comment by LeonieFierz** [comment]
the comment is fixed on master
