### ISSUE TITLE
Humidity reading too low

### ISSUE THREAD

**Issue by thaintrinh** [Sensirion/arduino-i2c-sht4x#8]
Hello,
I am using a custom board with SHT40-B and STC3X-C + Arduino UNO.
The Humidity sensor is giving me too low value of humidity. In the room, it should be ~50% (we have the evaluation board from Sensirion) meanwhile the sensor is giving only ~15%.
It used to work for several days and for some reasons, the humidity reading stopped working today.
I have also tried to exchange the sensor but still, it gives out the same result. 
On the other hand, the temperature values from the SHT41 are correct.
The sensor's Serial Number is: 0xEFD5F11
Please help.
Best,
Thai.

**Comment by thaintrinh** [comment]
I just exchanged the sensor to **SHT45-AD1B**. 
Funnily enough, with the same board, same code, same Arduino, the sensor spits out correct value again.
This is really strange, any help here would be really appreciated. 
Thanks in advance.

**Comment by psachs** [comment]
Hi,

A possible issue with low humidity readings, is that the SHT40 sensor got contaminated by the environment. A possible solution is to run the heater pulse for a couple seconds. You have to ensure that the temperature does not go over 120°C.

Please have a look at our applications notes about creep mitigation for more information:
https://sensirion.com/media/documents/A88858C9/629626D4/Application_Note_Creep_Mitigation_SHT4x.pdf

The creep mitigation document is about reversing issues when running the sensor in very humid environments. Something similar applies in case of "dirt" (e.g. dust) on the sensor. Running the heater can "burn" off the dirt and fix the issues.
Please note that the polymer used in SHT4x should not sprayed with e.g. cleaner as some of them can cause irreversible damage. Please have a look at the contamination guide for more information:
https://sensirion.com/media/documents/D1297BA5/670547C3/HT_AN_Contamination_Guide.pdf

**Comment by psachs** [comment]
I close this issue since it is not related to the driver code. Please contact Sensirion support directly if you need further assistance.
